application:
   version: v1.0
   title: dodowon
   
spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
    mode: HTML

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  cache:
    ehcache:
      config: classpath:ehcache.xml

mybatis:
  mapper-locations: classpath:/sqlmap/sqlmapper_*.xml

google:
  recaptcha:
    key:
      site: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      url: https://www.google.com/recaptcha/api/siteverify

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    websocket:
      enabled: false

server:
   error:
      include-stacktrace: always
      path: /error
      whitelabel:  
         eanbled: false
---
#개발 환경
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    schema: classpath:init.sql
    url: jdbc:mysql://localhost:3306/dodo_system?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: sangwon
    password: tkddnjs0823

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

file:
  upload-dir: D:\img

logging:
   config: classpath:logback-spring.xml  
---
#운영 환경
spring:
  profiles: env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dodo_system?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: sangwon
    password: tkddnjs0823

server:
  port: 8000
  servlet:
    session:
      timeout: 600s
      
file:
  upload-dir: D:\img