spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:/init.sql
    url: jdbc:mysql://localhost:3306/dodo_system?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: sangwon
    password: tkddnjs0823

  thymeleaf:
    cache: false
    mode: HTML

  devtools:
    livereload:
      enabled: true

mybatis:
  mapper-locations: classpath:/sqlmap/sqlmapper_*.xml